@startuml my_playlist
mainframe **sd** my_playlist
actor User


User --> ":Song" : create()
activate ":Song"
deactivate ":Song"

User -> ":Song" : str()
activate ":Song"
":Song" --> User
deactivate ":Song"

User --> ":Song" : create()
activate ":Song"
deactivate ":Song"

User --> ":Song" : create()
activate ":Song"
deactivate ":Song"

User --> ":Playlist" : create()
activate ":Playlist"
deactivate ":Playlist"

User --> ":Playlist" : add()
activate ":Playlist"
":Playlist" --> ":Song" : append()
activate ":Song"
deactivate ":Song"
":Playlist" -> ":Playlist": berechneAbspieldauer()
":Playlist" --> User
deactivate ":Playlist"

User --> ":Playlist" : add()
activate ":Playlist"
":Playlist" --> ":Song" : append()
activate ":Song"
deactivate ":Song"
":Playlist" -> ":Playlist": berechneAbspieldauer()
":Playlist" --> User
deactivate ":Playlist"

User --> ":Playlist" : add()
activate ":Playlist"
":Playlist" --> ":Song" : append()
activate ":Song"
deactivate ":Song"
":Playlist" -> ":Playlist": berechneAbspieldauer()
":Playlist" --> User
deactivate ":Playlist"

User -> ":Playlist" : str()
activate ":Playlist"
":Playlist" --> User
deactivate ":Playlist"

User -> ":Playlist" : getHaufigsterKuenstler())
activate ":Playlist"

loop
":Playlist" -> ":Playlist" : kuenstler_liste.append(kuenstler)
end

loop
":Playlist" -> ":Playlist" : kuenstler_count.append(kuenstler)
end

":Playlist" -> ":Playlist" : kuenstler_count.index(max(kuenstler_count))
":Playlist" --> User
deactivate ":Playlist"

User -> ":Playlist" : sucheSong()
activate ":Playlist"
":Playlist" --> User
deactivate ":Playlist"

User -> ":Playlist"
destroy ":Playlist"

User -> ":Song"
destroy ":Song"